SuperDuperHospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("db.urls")),
]

db/urls.py
from django.urls import path


from db.views import *


app_name = "db"
urlpatterns = [
    path("", PatientView.as_view(), name="index"),
    path("medicine", MedicineView.as_view(), name="medicine"),
    path("appointment", AppointmentView.as_view(), name="appointment"),
    path("accounting", AccountingView.as_view(), name="accounting"),
    path("disease", DiseaseView.as_view(), name="disease"),
    path("prescription", PrescriptionView.as_view(), name="prescription"),
    path("staff", StaffView.as_view(), name="staff"),
    path("sum", balance_sum_by_date_range, name="sum"),
    path("create_patient", create_patient, name="create_patient"),
    path("create_staff", create_staff, name="create_staff"),
    path("create_disease", CreateDisease.as_view(), name="create_disease"),
    path("edit_medicine/<int:pk>", EditMedicine.as_view(), name="edit_medicine"),
    path("create_medicine", CreateMedicine.as_view(), name="create_medicine"),
    path("create_appointment", CreateAppointment.as_view(), name="create_appointment"),
    path("create_accounting", CreateAccounting.as_view(), name="create_accounting"),
    path("delete_patient/<int:pk>", DeletePatient.as_view(), name="delete_patient"),
    path("edit_patient/<int:pk>", EditPatient.as_view(), name="edit_patient"),
    path("delete_staff/<int:pk>", DeleteStaff.as_view(), name="delete_staff"),
    path("edit_staff/<int:pk>", EditStaff.as_view(), name="edit_staff"),
    path("delete_disease/<int:pk>", DeleteDisease.as_view(), name="delete_disease"),
    path("edit_disease/<int:pk>", EditDisease.as_view(), name="edit_disease"),
    path("delete_appointment/<int:pk>", DeleteAppointment.as_view(), name="delete_appointment"),
    path("edit_appointment/<int:pk>", EditAppointment.as_view(), name="edit_appointment"),
    path("delete_medicine/<int:pk>", DeleteMedicine.as_view(), name="delete_medicine"),
    path("room", RoomView.as_view(), name="room"),
    path("edit_room/<int:pk>", EditRoom.as_view(), name="edit_room"),
    path("create_prescription", CreatePrescription.as_view(), name="create_prescription"),
    path("edit_prescription/<int:pk>", EditPrescription.as_view(), name="edit_prescription"),
    path("delete_prescription/<int:pk>", DeletePrescription.as_view(), name="delete_prescription"),
    path("remove_medicine/<int:pk>", delete_medicine, name="remove_medicine"),
]

db/models.py
from django.db import models


class Hospital(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=10)


class Department(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(Role, max_length=255)
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Patient(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=10)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    age = models.IntegerField()

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Room(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    room_number = models.IntegerField()
    patient = models.OneToOneField(Patient, null=True, on_delete=models.SET_NULL)


class Accounting(models.Model):
    balance = models.FloatField()
    date = models.DateTimeField()
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)


class Appointment(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    dateTime = models.DateTimeField()
    detail = models.CharField(max_length=255)


class Medicine(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    amount = models.IntegerField()

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Prescription(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)


class PrescriptionMedicine(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def __str__(self):
        return f"{self.medicine.name} {self.amount} units"

    def __repr__(self):
        return f"{self.medicine.name} {self.amount} units"


class Disease(models.Model):
    name = models.CharField(max_length=255)
    patient = models.ManyToManyField(Patient)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

db/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.base import View
from db.models import *
from db.filters import *
from db.forms import *


# Create your views here.


class PatientView(ListView):
    queryset = Patient.objects.all()
    template_name = "db/patient.html"
    context_object_name = "patients"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PatientFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.filterset.form
        context["create_form"] = PatientForm()
        return context


class PrescriptionMedicineView(ListView):
    queryset = PrescriptionMedicine.objects.all()
    template_name = "db/medicine.html"
    context_object_name = "medicines"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = MedicineFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.filterset.form
        context["create_form"] = CreateMedicineForm()
        return context


class AppointmentView(ListView):
    queryset = Appointment.objects.all().order_by("dateTime")
    template_name = "db/appointment.html"
    context_object_name = "appointments"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = AppointmentFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        context["create_form"] = AppointmentForm()
        context["create_form"].fields['staff'].queryset = Staff.objects.filter(role__name="Doctor")
        return context


class AccountingView(ListView):
    queryset = Accounting.objects.all().order_by("-date")
    template_name = "db/accounting.html"
    context_object_name = "accountings"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = AccountingFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        context["formsum"] = BalanceSumForm()
        context["create_form"] = AccountingForm()
        context["create_form"].fields['patient'].required = False
        return context


class DiseaseView(ListView):
    queryset = Disease.objects.all()
    template_name = "db/disease.html"
    context_object_name = "diseases"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = DiseaseFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        context["create_form"] = DiseaseForm
        return context


class PrescriptionView(ListView):
    queryset = Prescription.objects.all()
    template_name = "db/prescription.html"
    context_object_name = "prescriptions"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PrescriptionFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        context["create_form"] = PrescriptionForm()
        context["create_form"].fields['staff'].queryset = Staff.objects.filter(
            role__name="Doctor")
        return context


class StaffView(ListView):
    queryset = Staff.objects.all()
    template_name = "db/staff.html"
    context_object_name = "staffs"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = StaffFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        context["create_form"] = StaffForm()
        return context


def balance_sum_by_date_range(request):
    if request.method == 'POST':
        form = BalanceSumForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']

            # Query the database to get the sum of balances within the date range
            queryset = Accounting.objects.filter(date__range=(start_date, end_date))
            balance_sum = queryset.aggregate(Sum('balance'))['balance__sum']
            print(balance_sum)

            context = {
                'balance_sum': balance_sum,
                'queryset': queryset,
            }

            return render(request, 'db/balance_sum_result.html', context)


class MedicineView(ListView):
    queryset = Medicine.objects.all()
    template_name = "db/medicine.html"
    context_object_name = "medicines"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = MedicineFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.filterset.form
        context["create_form"] = CreateMedicineForm()
        return context


class EditMedicine(View):

    def get(self, request, pk):
        medicine = Medicine.objects.get(pk=pk)
        edit_form = MedicineEditForm(instance=medicine)
        context = {"medicine": medicine, "form": edit_form}
        return render(request, "db/edit_medicine.html", context)

    def post(self, request, pk):
        form = MedicineEditForm(request.POST, instance=Medicine.objects.get(pk=pk))
        if form.is_valid():
            form.save()
            return redirect('db:medicine')


class DeleteMedicine(View):
    def get(self, request, pk):
        Medicine.objects.get(pk=pk).delete()
        return redirect("db:medicine")


def create_patient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            diseases = form.cleaned_data['diseases']
            patient = form.save(commit=False)
            patient.save()
            for disease in diseases:
                patient.disease_set.add(disease)
            return redirect('db:index')


def create_staff(request):
    if request.method == 'POST':
        form = StaffForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('db:staff')


class CreateMedicine(View):

    def post(self, request):
        form = CreateMedicineForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('db:medicine')


class CreateDisease(View):

    def post(self, request):
        form = DiseaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('db:disease')


class CreateAppointment(View):

    def post(self, request):
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('db:appointment')


class CreateAccounting(View):

    def post(self, request):
        form = AccountingForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.hospital = Hospital.objects.get(id=1)
            account.save()
            return redirect('db:accounting')
        else:
            pat = form.cleaned_data.get("patient")
            expen = form.cleaned_data.get("is_expense")
            balance = form.cleaned_data.get("balance")
            date = form.cleaned_data.get("date")
            if pat is None and expen is True and balance < 0:
                account = Accounting(patient=None, balance=balance, date=date)
                account.hospital = Hospital.objects.get(id=1)
                account.save()
                print(account)
            return redirect('db:accounting')


class DeletePatient(View):

    def get(self, request, pk):
        patient = Patient.objects.get(pk=pk).delete()
        return redirect('db:index')


class EditPatient(View):

    def get(self, request, pk):
        patient = Patient.objects.get(pk=pk)
        edit_form = PatientForm(instance=patient)
        context = {"patient": patient, "form": edit_form}
        return render(request, "db/patient_edit.html", context)

    def post(self, request, pk):
        form = PatientForm(request.POST, instance=Patient.objects.get(pk=pk))
        if form.is_valid():
            diseases = form.cleaned_data['diseases']
            patient = form.save(commit=False)
            patient.save()
            for disease in diseases:
                patient.disease_set.add(disease)
            return redirect('db:index')


class DeleteStaff(View):

    def get(self, request, pk):
        staff = Staff.objects.get(pk=pk).delete()
        return redirect("db:staff")


class EditStaff(View):

    def get(self, request, pk):
        staff = Staff.objects.get(pk=pk)
        edit_form = StaffForm(instance=staff)
        context = {"staff": staff, "form": edit_form}
        return render(request, "db/staff_edit.html", context)

    def post(self, request, pk):
        form = StaffForm(request.POST, instance=Staff.objects.get(pk=pk))
        if form.is_valid():
            form.save()
            return redirect('db:staff')


class DeleteDisease(View):
    def get(self, request, pk):
        Disease.objects.get(pk=pk).delete()
        return redirect("db:disease")


class EditDisease(View):

    def get(self, request, pk):

db/templates/db/accounting.html
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>
{% block content %}
    {% include "base.html" %}
    <form hx-get="{% url "db:accounting" %}" hx-target='body' hx-trigger="input delay:500ms, change delay:500ms">
        <div class="card w-7/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                <div class="grid grid-cols-2 gap-4">
                    <h2>Date</h2>
                    <h2>Patient</h2>
                    <h2> {{ form.date }}</h2>
                    <h2> {{ form.patient__name }}</h2>
                </div>
                <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
        </div>
    </form>
    <div class="flex justify-center items-center mt-5">
        <div class="overflow-x-24 card w-7/12 mx-6 bg-base-100 shadow-xl">
            <div class="table-container max-h-96 overflow-y-auto rounded-lg">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for account in accountings %}
                        <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
                            {% if account.patient %}
                                <td class="font-semibold">{{ account.patient }}</td>
                            {% else %}
                                <td class="font-semibold">Expense</td>
                            {% endif %}
                            <td class="font-semibold">{{ account.balance }}</td>
                            <td class="font-semibold">{{ account.date }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <form hx-post="{% url "db:sum" %}" hx-target='#sum' hx-trigger="input delay:500ms, change delay:500ms">
        {% csrf_token %}
        <div class="card w-5/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                <h2 class="card-title">Balance summation</h2>
                <div class="grid grid-cols-2 gap-4">
                    {{ formsum.as_p}}
                </div>
                <div id="sum"></div>
            </div>
        </div>

    </form>
    <form method="post" action="{% url "db:create_accounting" %}">
        {% csrf_token %}
        <div class="card w-7/12 bg-base-200 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                <h2 class="card-title">Add New Invoice</h2>
                {{ create_form.media }}
                {{ create_form }}
                <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
        </div>
    </form>
{% endblock %}
<p>ㅤ</p>

</body>
</html>

db/templates/db/disease.html
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>
{% block content %}
    {% include "base.html" %}
    <form hx-get="{% url "db:disease" %}" hx-target='body' hx-trigger="input delay:500ms, change delay:500ms">
        <div class="card w-7/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                <div class="grid grid-cols-2 gap-4">
                    <h2>Disease Name</h2>
                    <h2> {{ form.name }}</h2>
                    <h2>Patient Name</h2>
                    <h2> {{ form.patient__name }}</h2>
                </div>
                <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
        </div>
    </form>
    <div class="flex justify-center items-center mt-5">
        <div class="overflow-x-24 card w-8/12 mx-6 bg-base-100 shadow-xl">
            <div class="table-container max-h-96 overflow-y-auto rounded-lg">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Disease Name</th>
                        <th>Patient Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for disease in diseases %}
                        <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
                            <td class="font-semibold">{{ disease.name }}</td>
                            <td class="font-semibold">
                            {% if disease.patient.all %}
                                {% for patient in disease.patient.all %}
                                    {{ patient }}
                                {% endfor %}
                            {% else %}
                            No patient having this disease
                            {% endif %}
                            <td><a href="{% url "db:edit_disease" disease.id %}">Edit</a><br>
                                <a href="{% url "db:delete_disease" disease.id %}">Delete</a> </td>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <form method="post" action="{% url "db:create_disease" %}">
        {% csrf_token %}
        <div class="card w-8/12 bg-base-200 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                <h2 class="card-title">Add New Disease</h2>
                <h2 class="card-title">Name {{ create_form.name }}</h2>
                <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
        </div>
    </form>
    <p>ㅤ</p>
{% endblock %}

</body>

db/templates/db/edit_prescription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prescription</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>
{% include "base.html" %}
<div class="flex justify-center items-center mt-5">
    <div class="overflow-x-24 card w-9/12 mx-6 bg-base-200 shadow-xl">
        <div class="table-container max-h-96 overflow-y-auto rounded-lg">
            <table class="table">
                <thead>
                <tr>
                    <th>Medicine</th>
                    <th>Amount</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for medicine in prescription %}
                    <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
                        <td>
                            {{ medicine.medicine }}
                        </td>
                        <td>
                            {{ medicine.amount }}
                        </td>
                        <td class="font-semibold">
                            <a href="{% url "db:remove_medicine" medicine.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<form method="post" action="{% url 'db:edit_prescription' pk %}">
    <div class="card w-8/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
        <div class="card-body items-center text-center">
            {% csrf_token %}
          {{ create_form }}
        <button type="submit" class="btn btn-active btn-secondary ml-5 mt-3">Add</button>
      </div>
    </div>
</form>
</body>
</html>

db/templates/db/medicine.html
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>
{% block content %}
{% include "base.html" %}
    <form hx-get="{% url "db:medicine" %}" hx-target='body'  hx-trigger="input delay:500ms, change delay:500ms">
        <div class="card w-7/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
              <h2 class="card-title">Medicine {{ form.name }}</h2>
                <h2 class="card-title">Department {{  form.prescriptionmedicine__prescription__staff__department__name }}</h2>
            <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
          </div>
    </form>
    <div class="flex justify-center items-center mt-5">
        <div class="overflow-x-24 card w-7/12 mx-6 bg-base-100 shadow-xl">
          <div class="table-container max-h-96 overflow-y-auto rounded-lg">
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for medicine in medicines %}
        <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
            <td class="font-semibold">{{ medicine.name }}</td>
            <td class="font-semibold">{{ medicine.price }}</td>
            <td class="font-semibold">{{ medicine.amount }}</td>
            <td class="font-semibold"><a href="{% url "db:edit_medicine" medicine.id %}">Edit</a><br>
            <a href="{% url "db:delete_medicine" medicine.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
            </div>
        </div>
    </div>
    <form method="post" action="{% url "db:create_medicine" %}">
    {% csrf_token %}
        <div class="card w-7/12 bg-base-100 shadow-xl mx-auto mt-5 text-center bg-base-200 ">
            <div class="card-body items-center text-center">
                <h2 class="card-title">Add New Medicine</h2>
                <h2 class="card-title">Medicine {{ create_form.name }}</h2>
                <h2 class="card-title">Price {{ create_form.price }}</h2>
                <h2 class="card-title">Amount {{ create_form.amount }}</h2>
                <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
        </div>
    </form>
    <p>ㅤ</p>
{% endblock %}
</body>
</html>

db/templates/db/prescription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prescription</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>
{% include "base.html" %}
    <form hx-get="{% url "db:prescription" %}" hx-target='body'  hx-trigger="input delay:500ms, change delay:500ms">
        <div class="card w-7/12 bg-base-200 shadow-xl mx-auto mt-5 text-center">
            <div class="card-body items-center text-center">
                {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
            </div>
          </div>
    </form>
<div class="flex justify-center items-center mt-5">
    <div class="overflow-x-24 card w-9/12 mx-6 bg-base-100 shadow-xl">
        <div class="table-container max-h-96 overflow-y-auto rounded-lg">
            <table class="table">
                <thead>
                <tr>
                    <th>Doctor</th>
                    <th>Patient</th>
                    <th>Medicine</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for prescription in prescriptions %}
                    <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
                        <td class="font-semibold">{{ prescription.staff }}</td>
                        <td>{{ prescription.patient }}</td>
                    <td>
                        {% for medicine in prescription.prescriptionmedicine_set.all %}
                        {{ medicine }},
                            {% endfor %}
                    </td>
                    <td class="font-semibold">
                        <a href="{% url "db:edit_prescription" prescription.id %}">Edit</a><br>
                        <a href="{% url "db:delete_prescription" prescription.id %}">Delete</a>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<form method="post" action="{% url 'db:create_prescription' %}">
    <div class="card w-8/12 bg-base-100 shadow-xl mx-auto mt-5 text-center">
        <div class="card-body items-center text-center">
            <h2 class="card-title">Add New Prescription</h2>
            {% csrf_token %}
          {{ create_form }}
        <button type="submit" class="btn btn-active btn-secondary ml-5 mt-3">Submit</button>
      </div>
    </div>
</form>
    <p>ㅤ</p>
</body>
</html>

db/templates/db/staff.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Staff</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.4/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
</head>
<body>

{% include "base.html" %}
<form hx-get="{% url "db:staff" %}" hx-target='body' hx-trigger="input delay:500ms, change delay:500ms">
    <div class="card w-7/12 bg-base-100 shadow-xl mx-auto mt-5 text-center bg-base-200">
        <div class="card-body items-center text-center">
            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-active btn-secondary ml-5 mt-3"/>
        </div>
    </div>
</form>
<div class="flex justify-center items-center mt-5">
    <div class="overflow-x-24 card w-9/12 mx-6 bg-base-100 shadow-xl">
        <div class="table-container max-h-96 overflow-y-auto rounded-lg">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Department</th>
                    <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for staff in staffs %}
                    <tr class="{% cycle 'bg-base-200' 'bg-base-300' %}">
                        <td class="font-semibold">{{ staff.name }}</td>
                        <td>{{ staff.role }}</td>
                        <td>{{ staff.department }}</td>
                        <td><a href="{% url "db:edit_staff" staff.id %}">Edit</a><br>
                        <a href="{% url "db:delete_staff" staff.id %}">Delete</a> </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<form method="post" action="{% url 'db:create_staff' %}">
        <div class="card w-8/12 bg-base-100 shadow-xl mx-auto mt-5 text-center bg-base-200">
            <div class="card-body items-center text-center">
                <h2 class="card-title">Add New Staff</h2>
                {% csrf_token %}
              {{ create_form }}
            <button type="submit" class="btn btn-active btn-secondary ml-5 mt-3">Submit</button>
          </div>
        </div>
    </form>
    <p>ㅤ</p>

</body>
</html>